name: crisis
description: A new Flutter project.

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text: ^1.0.2
  async: ^2.5.0
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  charts_flutter: ^0.10.0
  csc_picker: ^0.2.5
  cupertino_icons: ^1.0.2
  dart_twitter_api: ^0.5.3
  date_time_picker: ^2.0.0
  delayed_display: ^2.0.0
  dio: ^4.0.0
  dotted_line: ^3.0.0
  dropdown_search: ^0.6.1
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_dropdown: ^0.0.8
  flutter_native_splash: ^1.1.8+4
  flutter_rating_bar: ^4.0.0
  flutter_redux: ^0.8.2
  flutter_screenutil: ^5.0.0+2
  flutter_sparkline: ^0.1.0
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  grouped_list: ^4.0.0
  http: ^0.13.1
  intl: ^0.17.0
  json_serializable: ^4.1.1
  number_display: ^3.0.0
  pin_code_fields: ^7.0.0
  redux: ^5.0.0
  share_plus: ^2.0.3
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  youtube_player_iframe: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
